import glob
import os

import numpy as np

from mwr_l12l2.utils.config_utils import get_inst_config, get_mars_config, merge_mars_inst_config
from mwr_l12l2.utils.file_uitls import abs_file_path


def write_mars_request(request_file, mars_conf, inst_conf_path, inst_conf_file_pattern='config_0*.yaml'):
    """write request file for getting ECMWF model data using 'mars' for all stations that have a valid config file"""

    # get config files ready
    if not isinstance(mars_conf, dict):
        mars_conf = get_mars_config(abs_file_path(mars_conf))
    inst_conf_path = abs_file_path(inst_conf_path)
    inst_conf_files = glob.glob(os.path.join(inst_conf_path, inst_conf_file_pattern))

    # initialise list of file contents. It is a list of strings, one for each line (omit tailing commas)
    contents = ['# CARE: This file is automatically generated by {}. Do not edit.'.format(__file__)]
    contents.append('')
    contents.append('retrieve,' )

    # define part of request common to all stations
    for key, val in mars_conf['request'].items():
        contents.append('  {}={},'.format(key, val))

    # define one request per stations (keys that are not re-set will be taken from previous request)
    for ind, inst_conf_file in enumerate(inst_conf_files):

        inst_conf = get_inst_config(inst_conf_file)
        conf = merge_mars_inst_config(mars_conf, inst_conf)
        lat_box = get_corner_coord(inst_conf['station_latitude'], conf['grid']['lat_offset'], conf['grid']['lat_res'])
        lon_box = get_corner_coord(inst_conf['station_longitude'], conf['grid']['lon_offset'], conf['grid']['lon_res'])

        if ind > 0:
            contents.append('retrieve,')
        contents.append('  grid={}/{},'.format(conf['grid']['lat_res'], conf['grid']['lon_res']))
        contents.append('  area={:.2f}/{:.2f}/{:.2f}/{:.2f},'.format(lat_box[1], lon_box[0], lat_box[0], lon_box[1]))
        contents.append('')
        # TODO: define target (output filename)

    with open(request_file, 'w') as f:
        f.write('\n'.join(contents))


def get_corner_coord(stn_coord, offset, resol):
    """get corners of a coordinate box around station coordinates which match model grid points"""
    stn_coord_rounded = round(stn_coord/resol) * resol  # round centre coordinate to model resolution
    return stn_coord_rounded + np.array(offset)


if __name__ == '__main__':
    write_mars_request('dummy_mars_request.txt', 'mwr_l12l2/config/mars_config.yaml', 'mwr_l12l2/config/')