# config file example for a Radiometrics MP3000 in Lindenberg, Germany #
########################################################################

input_directory: tbd  # use absolute path (or relative to mwr_l12l1 project dir)
output_directory: tbd  # use absolute path (or relative to mwr_l12l1 project dir)
base_filename_in: MWR_1C01_0-20000-0-10393_A
base_filename_out: MWR_tbd_0-20000-0-10393_A

# the following keys are most possibly duplicates of the input file's attributes. If both exist, should be used to check
wigos_station_id: 0-20000-0-10393
instrument_id: A
station_latitude: 52.21
station_longitude: 14.12
station_altitude: 98.

# the following can be used to deviate from the standard defined in mars_config_fc.yaml for requesting model data.
model_request:
  grid:
    lat_res: 0.1  # latitude resolution with which to write values to the output file
    lon_res: 0.1  # longitude resolution with which to write values to the output file
    lat_offset: [-0.1, 0.1]  # corners of box relative to station within which to get model data for mean and std
    lon_offset: [-0.1, 0.1]  # corners of box relative to station within which to get model data for mean and std
#  outfile: # do not set unless you have a very good reason to deviate from default defined in mars_config_fc.yaml
#     path:
#     basename:
#     extension:

retrieval:
  tb_noise: [0.30, 0.30, 0.30, 0.30, 0.30, 0.30, 0.30, 0.30,
             0.70, 0.70, 0.70, 0.70, 0.70, 0.40, 0.40, 0.40, 0.40, 0.40, 0.40, 0.25, 0.25, 0.25]
  tb_bias: [5.20, -1.35, -0.17, 0.47, 1.75, 0.29, 0.60, -3.75,
            2.12, 1.57, 3.50, 3.99, 3.38, 1.44, -0.14, 0.16, -0.15, -0.08, 0.39, 0.96, -0.42, 0.34]
  zenith_channels: [True, True, True, True, True, True, True, True,
                    True, True, True, True, True, True, True, True, True, True, True, True, True, True]
  scan_channels: [False, False, False, False, False, False, False, False,
                  False, False, False, False, False, False, False, False, False, False, False, True, True, True]
  scan_ele: [19.8, 160.2]