# config file example for a RPG HATPRO in Payerne, Switzerland #
################################################################

input_directory: tbd  # use absolute path (or relative to mwr_l12l1 project dir)
output_directory: tbd  # use absolute path (or relative to mwr_l12l1 project dir)
base_filename_in: MWR_1C01_0-20000-0-06610_A
base_filename_out: MWR_tbd_0-20000-0-06610_A

# the following keys are most possibly duplicates of the input file's attributes. If both exist, they are used to check
wigos_station_id: 0-20000-0-06610
instrument_id: A
station_latitude: 46.81
station_longitude: 6.94
station_altitude: 491.

# the following can be used to deviate from the standard defined in mars_config.yaml for requesting model data.
model_request:
   grid:
      lat_res: 0.1  # latitude resolution with which to write values to the output file
      lon_res: 0.1  # longitude resolution with which to write values to the output file
      lat_offset: [-0.1, 0.1]  # corners of box relative to station within which to get model data for mean and std
      lon_offset: [-0.1, 0.1]  # corners of box relative to station within which to get model data for mean and std
#   outfile: # do not set unless you have a very good reason to deviate from default defined in mars_config.yaml
#      path:
#      basename:
#      extension: