# config file example for a RPG HATPRO in Lille, France #
################################################################

input_directory: tbd  # use absolute path (or relative to mwr_l12l1 project dir)
output_directory: tbd  # use absolute path (or relative to mwr_l12l1 project dir)
base_filename_in: MWR_1C01_0-50-250-1006-98518_A
base_filename_out: MWR_tbd_0-50-250-1006-98518_A

# the following keys are most possibly duplicates of the input file's attributes. If both exist, should be used to check
wigos_station_id: 50-250-1006-98518
instrument_id: A
station_latitude: 50.61
station_longitude: 3.14
station_altitude: 15.

# the following can be used to deviate from the standard defined in mars_config_fc.yaml for requesting model data.
model_request:
  grid:
    lat_res: 0.1  # latitude resolution with which to write values to the output file
    lon_res: 0.1  # longitude resolution with which to write values to the output file
    lat_offset: [-0.1, 0.1]  # corners of box relative to station within which to get model data for mean and std
    lon_offset: [-0.1, 0.1]  # corners of box relative to station within which to get model data for mean and std
#  outfile: # do not set unless you have a very good reason to deviate from default defined in mars_config_fc.yaml
#     path:
#     basename:
#     extension:

retrieval:
  tb_noise: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
             6, 6, 0.6, 0.4, 0.25, 0.25, 0.25]
  tb_bias: [0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0.]
  

  #tb_bias: [2.23 , 2.65,  3.85 , 3.65,  4.01,  3.34,  3.01,  9.3,  11.07,  4.43 ,-0.2 , -0.25,-0.12 ,-0.06]
  zenith_channels: [True, True, True, True, True, True, True,
                    True, True, True, True, True, True, True]
  scan_channels: [False, False, False, False, False, False, False,
                 False, False, False, False, False, False, False] # must exactly match values in freq_used
  scan_ele: []  # TODO: implement a 2-sided ele-search for getting ele around 5, 10, and 20 deg for all instruments (rather configure in retrieval_config)