# config file for defining the format of the output L2 NetCDF #
###############################################################

dimensions:
  unlimited:
    - time  # refers to variable name in data dictionary
  fixed:
    - altitude

variables:
  time:  # variable name in Measurement.data Dataset
    name: time  # variable name in output NetCDF
    dim:
      - time
    type: f8
    _FillValue: null
    optional: False
    attributes:
      long_name: Time (UTC) of the measurement
      standard_name: time
      units: seconds since 1970-01-01 00:00:00
      calendar: standard
      bounds: time_bnds
      comment: Time indication of samples is at the end of integration time

  altitude:
    name: altitude
    dim:
      - altitude
    type: f4
    _FillValue: -999.
    optional: False
    attributes:
      long_name: Altitude above mean sea level
      standard_name: altitude
      units: m

  lat:
    name: station_latitude
    dim:
      - time
    type: f4
    _FillValue: -999.
    optional: False
    attributes:
      long_name: Latitude of measurement station
      standard_name: latitude
      units: degree_north

  lon:
    name: station_longitude
    dim:
      - time
    type: f4
    _FillValue: -999.
    optional: False
    attributes:
      long_name: Longitude of measurement station
      standard_name: longitude
      units: degree_east

  # TODO: add quality_flag and quality_flag_status, possibly also freq-dependent vars

  temperature:
    name: temperature
    dim:
      - time
      - altitude
    type: f4
    _FillValue: -999.
    optional: True  #n none of the retrieved fields can be mandatory as T/q-only MWR's exist
    attributes:
      long_name: Retrieved temperature profile
      standard_name: air_temperature
      units: K

  water_vapor_vmr:
    name: water_vapor_vmr
    dim:
      - time
      - altitude
    type: f4
    _FillValue: -999.
    optional: True
    attributes:
      long_name: Retrieved water vapour profile
      units: g/kg
      # TODO should probably transform this to ppm to comply with the format definition doc. Synchronise with this document
      # TODO: check for standard name and adequate units: https://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html

  lwp:
    name: lwp
    dim:
      - time
    type: f4
    _FillValue: -999.
    optional: True
    attributes:
      long_name: Retrieved column-integrated liquid water path
      units: mm

  pwv:
    name: iwv
    dim:
      - time
    type: f4
    _FillValue: -999.
    optional: True
    attributes:
      long_name: Calculated column-integrated liquid water path
      comment: calculated from retrieved profile in water_vapor_vmr
      units: mm

  mlCAPE:
    name: cape
    dim:
      - time
    type: f4
    _FillValue: -9999.  # TODO: this matches tropoe output. think of transforming to -999. for consistency
    optional: True
    attributes:
      long_name: Convective available potential energy
      comment: calculated from retrieved profiles
      units: 1

  mlCIN:
    name: cin
    dim:
      - time
    type: f4
    _FillValue: -9999.  # TODO: this matches tropoe output. think of transforming to -999. for consistency
    optional: True
    attributes:
      long_name: Convective inhibition
      comment: calculated from retrieved profiles
      units: 1

  mlLCL:
    name: lcl
    dim:
      - time
    type: f4
    _FillValue: -9999.  # TODO: this matches tropoe output. think of transforming to -999. for consistency
    optional: True
    attributes:
      long_name: Convective inhibition
      comment: calculated from retrieved profiles
      units: m

  # TODO: add errors to quantities and decide whether to report as random error or systematic error

# global attributes common to all instruments. Additional instrument-specific attrs in their config under nc_attributes.
# If the same fields are present in the instrument-specific config, the general ones from below will be overwritten
attributes:
  Conventions: CF-1.8
  references: E-PROFILE data format description document
  license: Closed-Use Non-Commercial General Licence 1.0 (CUNCGL)
  network_name: E-PROFILE
  campaign_name: ''
  comment: ''
  source: Ground Based Remote Sensing
  dependencies: None
  # history is directly set in NetCDF writer
