# config file for defining the format of the output L2 NetCDF #
###############################################################

dimensions:
  unlimited:
    - time  # refers to variable name in data dictionary
  fixed:
    - altitude

variables:
  time:  # variable name in Measurement.data Dataset
    name: time  # variable name in output NetCDF
    dim:
      - time
    type: f8
    _FillValue: null
    optional: False
    attributes:
      long_name: Time (UTC) of the measurement
      standard_name: time
      units: seconds since 1970-01-01 00:00:00
      calendar: standard
      bounds: time_bnds
      comment: Time indication of samples is at the end of integration time

  altitude:
    name: altitude
    dim:
      - altitude
    type: f4
    _FillValue: -999.
    optional: False
    attributes:
      long_name: Altitude above mean sea level
      standard_name: altitude
      units: m

  lat:
    name: station_latitude
    dim:
      - time
    type: f4
    _FillValue: -999.
    optional: False
    attributes:
      long_name: Latitude of measurement station
      standard_name: latitude
      units: degree_north

  lon:
    name: station_longitude
    dim:
      - time
    type: f4
    _FillValue: -999.
    optional: False
    attributes:
      long_name: Longitude of measurement station
      standard_name: longitude
      units: degree_east

  # in this case, the variable has already been created 
  station_altitude:
    name: surface_altitude
    dim:
      - time
    type: f4
    _FillValue: -999.
    optional: False
    attributes:
      long_name: Altitude above mean sea level of measurement station
      standard_name: surface_altitude
      units: m

  # azi: to propagate from L1 !
  #   name: azimuth_angle
  #   dim:
  #     - time
  #   type: f4
  #   _FillValue: -999.
  #   optional: False
  #   attributes:
  #     long_name: Sensor azimuth angle
  #     standard_name: sensor_azimuth_angle 
  #     units: degree
  #     comment: “0=North, 90=East, 180=South, 270=West”
  
  # TODO: add quality_flag and quality_flag_status, possibly also freq-dependent vars

  # TODO: Add time bnds, is there a straightforward solution for multiple time retrieval ?

##########################################################################################################
# QC fields
##########################################################################################################
  
  qc_flag:
    name: qc_flag
    dim:
      - time
    type: f4
    _FillValue: -999.
    optional: True
    attributes:
      long_name: Quality flag
      comment: ''
      units: "1"


##########################################################################################################
# Temperature fields 
##########################################################################################################

  temperature:
    name: temperature
    dim:
      - time
      - altitude
    type: f4
    _FillValue: -999.
    optional: True  # none of the retrieved fields can be mandatory as T/q-only MWR's exist
    attributes:
      long_name: Retrieved temperature profile
      standard_name: air_temperature
      units: K

  temperature_prior:
    name: temperature_apriori
    dim:
      - time
      - altitude
    type: f4
    _FillValue: -999.
    optional: True
    attributes:
      long_name: A priori temperature profile of retrieval
      units: K

  sigma_temperature:
    name: temperature_random_error
    dim:
      - time
      - altitude
    type: f4
    _FillValue: -999.
    optional: True  # none of the retrieved fields can be mandatory as T/q-only MWR's exist
    attributes:
      long_name: Random uncertainty of retrieved temperature profile
      units: K

  # temperature_systematic_error:
  #   name: temperature
  #   dim:
  #     - time
  #     - altitude
  #   type: f4
  #   _FillValue: -999.
  #   optional: True  # none of the retrieved fields can be mandatory as T/q-only MWR's exist
  #   attributes:
  #     long_name: Systematic uncertainty of retrieved temperature profile
  #     standard_name: temperature_systematic_error
  #     units: K

##########################################################################################################
# Water Vapor fields
##########################################################################################################

  waterVapor:
    name: humidity_mixing_ratio
    dim:
      - time
      - altitude
    type: f4
    _FillValue: -999.
    optional: True
    attributes:
      standard_name: humidity_mixing_ratio
      long_name: Retrieved water vapour profile
      units: kg kg-1
      # TODO should probably transform this to ppm to comply with the format definition doc. Synchronise with this document
      # TODO: check for standard name and adequate units: https://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html

  waterVapor_prior:
    name: humidity_mixing_ratio_apriori
    dim:
      - time
      - altitude
    type: f4
    _FillValue: -999.
    optional: True
    attributes:
      long_name: A priori water vapour profile of retrieval
      units: kg kg-1

  sigma_waterVapor:
    name: humidity_mixing_ratio_random_error
    dim:
      - time
      - altitude
    type: f4
    _FillValue: -999.
    optional: True
    attributes:
      long_name: Random uncertainty of retrieved water vapour profile
      units: kg kg-1
      # TODO should probably transform this to ppm to comply with the format definition doc. Synchronise with this document
      # TODO: check for standard name and adequate units: https://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html


  rh:
    name: relative_humidity
    dim:
      - time
      - altitude
    type: f4
    _FillValue: -999.
    optional: True
    attributes:
      long_name: Relative Humidity
      standard_name: relative_humidity
      units: "1"
      comment: derived from retrieved fields

  theta:
    name: potential_temperature
    dim:
      - time
      - altitude
    type: f4
    _FillValue: -999.
    optional: True
    attributes:
      long_name: Potential Temperature
      standard_name: air_potential_temperature
      units: K
      comment: derived from retrieved fields

  thetae:
    name: equivalent_potential_temperature
    dim:
      - time
      - altitude
    type: f4
    _FillValue: -999.
    optional: True
    attributes:
      long_name: Equivalent potential temperature
      standard_name: air_equivalent_potential_temperature
      units: K
      comment: derived from retrieved fields

  dewpt:
    name: dew_point_temperature
    dim:
      - time
      - altitude
    type: f4
    _FillValue: -999.
    optional: True
    attributes:
      long_name: Dew point temperature
      standard_name: dew_point_temperature
      units: K
      comment: derived from retrieved fields

##########################################################################################################
# Measurement related fields
##########################################################################################################
  rmsr:
    name: rmsr
    dim:
      - time
    type: f4
    _FillValue: -999.
    optional: True
    attributes:
      long_name: Root mean square error between IRS and MWR obs in the observation vector and the forward calculation
      units: "1"

##########################################################################################################
# Integrated fields
##########################################################################################################

  lwp:
    name: lwp
    dim:
      - time
    type: f4
    _FillValue: -999.
    optional: True
    attributes:
      standard_name: atmosphere_cloud_liquid_water_content 
      long_name: Retrieved column-integrated liquid water path
      comment: Derived from zenith observations
      # TODO: indicate source
      units: kg m-2

  lwp_prior:
    name: lwp_apriori
    dim:
      - time
    type: f4
    _FillValue: -999.
    optional: True
    attributes:
      long_name: A priori value for column-integrated liquid water path
      # TODO: indicate source
      units: kg m-2

  sigma_lwp:
    name: lwp_random_error
    dim:
      - time
    type: f4
    _FillValue: -999.
    optional: True
    attributes:
      long_name: Random uncertainty of retrieved column-integrated liquid water path
      units: kg m-2

  pwv:
    name: iwv
    dim:
      - time
    type: f4
    _FillValue: -999.
    optional: True
    attributes:
      standard_name: atmosphere_mass_content_of_water_vapor
      long_name: Column-integrated water vapour
      comment: calculated from retrieved profile in water_vapor_vmr
      units: kg m-2

  sigma_pwv:
    name: iwv_random_error
    dim:
      - time
    type: f4
    _FillValue: -999.
    optional: True
    attributes:
      long_name: Random uncertainty of column-integrated water vapour
      units: kg m-2

##########################################################################################################
# Forecast indices
##########################################################################################################

  mlCAPE:
    name: cape
    dim:
      - time
    type: f4
    _FillValue: -9999.  # TODO: this matches tropoe output. think of transforming to -999. for consistency
    optional: True
    attributes:
      standard_name: atmosphere_convective_available_potential_energy
      long_name: Convective available potential energy for a mixed-layer parcel
      #comment: calculated from retrieved profiles
      units: J kg-1

  sigma_mlCAPE:
    name: cape_random_error
    dim:
      - time
    type: f4
    _FillValue: -999.  # TODO: this matches tropoe output. think of transforming to -999. for consistency
    optional: True
    attributes:
      long_name: 1-sigma uncertainties in mixed-layer CAPE
      #comment: calculated from retrieved profiles
      units: J kg-1

  mlCIN:
    name: cin
    dim:
      - time
    type: f4
    _FillValue: -9999.  # TODO: this matches tropoe output. think of transforming to -999. for consistency
    optional: True
    attributes:
      standard_name: atmosphere_convective_inhibition
      long_name: Convective inhibition for a mixed-layer parcel
      #comment: calculated from retrieved profiles
      units: J kg-1

  sigma_mlCIN:
    name: cin_random_error
    dim:
      - time
    type: f4
    _FillValue: -9999.  # TODO: this matches tropoe output. think of transforming to -999. for consistency
    optional: True
    attributes:
      standard_name: atmosphere_convective_inhibition
      long_name: 1-sigma uncertainties in mixed-layer CIN
      #comment: calculated from retrieved profiles
      units: J kg-1

  mlLCL:
    name: lcl
    dim:
      - time
    type: f4
    _FillValue: -9999.  # TODO: this matches tropoe output. think of transforming to -999. for consistency
    optional: True
    attributes:
      standard_name: atmosphere_level_of_free_convection
      long_name: Lifted condensation level
      #comment: calculated from retrieved profiles
      units: m

  sigma_mlLCL:
    name: lcl_random_error
    dim:
      - time
    type: f4
    _FillValue: -9999.  # TODO: this matches tropoe output. think of transforming to -999. for consistency
    optional: True
    attributes:
      long_name: 1-sigma uncertainties in the LCL for a mixed-layer parcel
      #comment: calculated from retrieved profiles
      units: m

  # TODO: add errors to quantities and decide whether to report as random error or systematic error

# global attributes common to all instruments. Additional instrument-specific attrs in their config under nc_attributes.
# If the same fields are present in the instrument-specific config, the general ones from below will be overwritten
attributes:
  Conventions: CF-1.8
  references: E-PROFILE data format description document (v01.9)
  license: Closed-Use Non-Commercial General Licence 1.0 (CUNCGL)
  network_name: E-PROFILE
  campaign_name: ''
  comment: ''
  source: Ground Based Remote Sensing
  dependencies: None
  # retrieval_type: optimal estimation -> to be set at each retrieval
  # history is directly set in NetCDF writer
