# config file for general retrieval settings #
##############################################
#
# the data section contains paths of data files and age of data to consider
# the vip section contains configurations for the TROPoe retrieval
# this file defines the settings common to all stations.

# definitions of which data to use for retrieval. Paths are absolute or relative to mwr_l12l2 project dir
data:

  # maximum age of MWR data to be considered for retrieval in minutes. Set to null for unlimited
  max_age: 90

  # location and filenames of E-PROFILE data
  mwr_dir: mwr_l12l2/data/mwr/  # directory for microwave radiometer input data
  mwr_file_prefix: MWR_1C01_
  alc_dir: mwr_l12l2/data/alc/  # directory for automatic lidar's or ceilometer's cloud base input data
  alc_file_prefix: L2_

  # location and filename of model data (does not have to match outfile of mars config, will be put here by sort_model)
  # TODO: write sort_model (put mars output to right location and run grb_to_nc) and sort_eprofile (get from FTP)
  model_dir: mwr_l12l2/data/ecmwf_fc/  # directory for NWP model input data
  model_fc_file_prefix: ecmwf_fc_
  model_fc_file_suffix: _converted_to  # for file converted from grib to NetCDF
  model_fc_file_ext: .nc
  model_z_file_prefix: ecmwf_z_
  model_z_file_ext: .grb

  # location and filenames of temporary TROPoe files
  tropoe_basedir: mwr_l12l2/data/tropoe/  # base directory where folder with tmp files for tropoe runs is saved
  tropoe_subfolder_basename: node_  # basename of subfolders for different (parallel) TROPoe runs
  vip_filename_tropoe: vip.txt
  mwr_filename_tropoe: mwr.nc
  alc_filename_tropoe: alc.nc
  model_prof_filename_tropoe: model_prof.nc
  model_sfc_filename_tropoe: model_sfc.nc

# general settings for TROPoe's vip files (must match vip keywords; do not set paths, taken from data.*tropoe* above)
vip:
  testkey: testval
  # TODO: add vip config here and in config_utils.get_retrieval_config and remove testkey: testval above
