# Config file for reading TROPoe output
################################################################

# Manual description of the retrieval quantities and corresponding indices in arbitrary dimension variables
# It should remains essentially constant except if we change the retrieval setup
temperature: 1
waterVapor: 2
lwp: 3
lReff: 4
iTau: 5
iReff: 6
co2: 7
ch4: 8
n2o: 9

# The same for the obsevation vector, defined in the obs_dimension variables of the TROPoe output
radianceWN: 1
zenithTb: 2
scanTb: 10
surfaceT: 5
modelT: 7
modelWV: 8

